---
title: "hw3"
author: "Sarayu Ramnath"
editor: visual
date: 2026-01-25
editor_options: 
  chunk_output_type: console
format:
  pdf:
    pdf-engine: xelatex
    theme: cerulean
knitr:
  opts_chunk:
    warning: false
    message: false
---

## Set Up 

```{r}

library(tidyverse)
library(ggplot2)
library(janitor)
library(dplyr)


# #....Step 1a: see all available ACS variables + descriptions.....
# acs_vars <- tidycensus::load_variables(year = 2023,
#                                        dataset = "acs1")
# 
# #..............Step 1b: import race & ethnicity data.............
# race_ethnicity <- tidycensus::get_acs(
#   geography = "county",
#   survey = "acs1",
#   # NOTE: you may not end up using all these variables
#   variables = c("B01003_001", "B02001_002", "B02001_003", 
#                 "B02001_004", "B02001_005", "B02001_006",
#                 "B02001_007", "B02001_008", "B03002_012",
#                 "B03002_002"),
#   state = "CA", 
#   year = 2023) |>
#   # join variable descriptions (so we know what's what!)
#   dplyr::left_join(acs_vars, by = dplyr::join_by(variable == name)) 
# 
# #.................Step 2: write ACS data to file.................
# readr::write_csv(race_ethnicity, here::here("data", "ACS-1yr-2023-county-race-ethnicity.csv"))
# 
# #..................Step 3: read in your CSV file.................
# race_ethnicity <- readr::read_csv(here::here("data", "ACS-1yr-2023-county-race-ethnicity.csv"))
```

## Objective

***How does climate hazard risk exposure vary across racial / ethnic groups in California?*** 

```{r}

#nri_raw <- read_csv("data/nri_counties.csv")


nri_ca_race_raw <- nri_raw |>
  select(1:17) |>
  filter(state_fips_code == "06") |>
  left_join(
    race_ethnicity,
    by = c("state_county_fips_code" = "GEOID")
  )

#n_distinct(nri_ca_race$state_county_fips_code) should return 58== 58 counties 

#clean up nri_ca_race set and then save to data 
readr::write_csv(nri_ca_race_raw, here::here("data", "nri_ca_race_raw"))



```

You can add options to executable code like this

```{r}
#| echo: false
2 * 2
```

The `echo: false` option disables the printing of code (only output is displayed).
